### ISSUE TITLE
"postinstall" script is executed by consumers of published packages

### ISSUE THREAD

**Issue by sondreb** [tomchen/example-typescript-package#1]
Using this template will publish a package.json that contains the following script:

```"postinstall": "husky install",```

This will also run when the published package is consumed.

Not sure if there is a step I'm missing, or if this is an fault with the template?

**Comment by tomchen** [comment]
I always use yarn 1. It appears yarn 2 is a little different. From [husky docs, section yarn 2](https://typicode.github.io/husky/#/?id=yarn-2):
> If your package is not private and you're publishing it on a registry like npmjs.com, you need to disable postinstall script using pinst. Otherwise, postinstall will run when someone installs your package and result in an error.

Use [**pinst**](https://github.com/typicode/pinst) in your package to make husky dev only.

I'll update the template and the readme.

**Comment by tomchen** [comment]
It had error when being installed no matter user uses yarn 1 or 2+ or npm.

Now after 8887dc8 where I installed [pinst](https://github.com/typicode/pinst), everything is fine. I [tested](https://github.com/tomchen/example-typescript-package-test/actions/runs/1237265245) the installation of the package with npm, yarn v1 and yarn v2+, in ubuntu, win and node 12, 14, 16.
